# Generated by Django 5.1 on 2025-03-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('labels', models.ManyToManyField(related_name='papers', to='PaperSummarizer.label')),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaperSummarizer.summary')),
            ],
        ),
    ]
