# Generated by Django 5.1 on 2025-03-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0002_label_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
