# Generated by Django 5.1 on 2025-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0003_alter_label_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='key_words',
            field=models.JSONField(default=list),
        ),
    ]
