# Generated by Django 5.1 on 2025-03-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0004_paper_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
    ]
