# Generated by Django 5.1 on 2025-03-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0005_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='key_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='papers', to='PaperSummarizer.label'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PaperSummarizer.summary'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='latex_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
