# Generated by Django 5.1 on 2025-03-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperSummarizer', '0006_alter_paper_key_words_alter_paper_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='papers', to='PaperSummarizer.label'),
        ),
    ]
